#!/usr/bin/env python3
"""Render a human/LLM-readable capability matrix from custom-elements.json.

The target Modus repository should copy or adapt this script into its own build
and drift-check path. It intentionally reports only facts present in the
manifest; it does not infer capabilities from sibling components.
"""

from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path
from typing import Any, Iterable


def _text(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, dict):
        return str(value.get("text") or value.get("name") or "")
    return str(value)


def _cell(value: Any) -> str:
    return _text(value).replace("|", "\\|").replace("\n", " ").strip()


def _pointer(*parts: Any) -> str:
    escaped = [str(part).replace("~", "~0").replace("/", "~1") for part in parts]
    return "#/" + "/".join(escaped)


def _is_readonly(name: str) -> bool:
    normalized = re.sub(r"[-_]", "", name.casefold())
    return normalized == "readonly"


def _modules(manifest: dict[str, Any]) -> Iterable[tuple[int, dict[str, Any]]]:
    modules = manifest.get("modules")
    if isinstance(modules, list):
        return ((index, module) for index, module in enumerate(modules) if isinstance(module, dict))
    return ()


def _declarations(
    manifest: dict[str, Any],
) -> Iterable[tuple[str, dict[str, Any]]]:
    for module_index, module in _modules(manifest):
        declarations = module.get("declarations") or []
        if not isinstance(declarations, list):
            continue
        for declaration_index, declaration in enumerate(declarations):
            if not isinstance(declaration, dict):
                continue
            tag = declaration.get("tagName") or declaration.get("tag")
            if not isinstance(tag, str) or not tag.strip():
                continue
            yield (
                _pointer("modules", module_index, "declarations", declaration_index),
                declaration,
            )


def _members(declaration: dict[str, Any]) -> list[dict[str, Any]]:
    members = declaration.get("members") or []
    if not isinstance(members, list):
        return []
    return [member for member in members if isinstance(member, dict) and member.get("name")]


def _properties(declaration: dict[str, Any]) -> list[dict[str, Any]]:
    properties = [
        member
        for member in _members(declaration)
        if member.get("kind") not in {"method", "event"}
    ]
    attributes = declaration.get("attributes") or []
    if isinstance(attributes, list):
        properties.extend(
            attribute
            for attribute in attributes
            if isinstance(attribute, dict) and attribute.get("name")
        )
    return sorted(properties, key=lambda item: str(item.get("name")).casefold())


def _events(declaration: dict[str, Any]) -> list[dict[str, Any]]:
    events = declaration.get("events") or []
    if not isinstance(events, list):
        return []
    return sorted(
        [event for event in events if isinstance(event, dict) and event.get("name")],
        key=lambda item: str(item.get("name")).casefold(),
    )


def _slots(declaration: dict[str, Any]) -> list[dict[str, Any]]:
    slots = declaration.get("slots") or []
    if not isinstance(slots, list):
        return []
    normalized: list[dict[str, Any]] = []
    for slot in slots:
        if isinstance(slot, str):
            normalized.append({"name": slot})
        elif isinstance(slot, dict) and slot.get("name") is not None:
            normalized.append(slot)
    return sorted(normalized, key=lambda item: str(item.get("name")).casefold())


def render(manifest: dict[str, Any], *, source_commit: str, generated_at: str) -> str:
    components = sorted(
        (
            (str(declaration.get("tagName") or declaration.get("tag")), pointer, declaration)
            for pointer, declaration in _declarations(manifest)
        ),
        key=lambda item: item[0].casefold(),
    )
    lines = [
        "# Modus custom-elements capability matrix",
        "",
        f"**Generated by:** `render_custom_elements.py`  ",
        "**Source:** `src/custom-elements.json`  ",
        f"**Source commit:** `{_cell(source_commit)}`  ",
        f"**Generated at:** `{_cell(generated_at)}`  ",
        "",
        "This file is derived from the source manifest. A missing property means",
        "it was not listed in the inspected manifest; do not infer support from",
        "a sibling component.",
        "",
        "## Component index",
        "",
        "| Tag | Declaration | Manifest source | Supports `readonly` |",
        "| --- | --- | --- | --- |",
    ]
    for tag, pointer, declaration in components:
        names = [str(member.get("name")) for member in _properties(declaration)]
        readonly = "yes" if any(_is_readonly(name) for name in names) else "no"
        lines.append(
            f"| `<{_cell(tag)}>` | `{_cell(declaration.get('name'))}` | "
            f"`src/custom-elements.json{pointer}` | `{readonly}` |"
        )

    for tag, pointer, declaration in components:
        properties = _properties(declaration)
        events = _events(declaration)
        slots = _slots(declaration)
        names = [str(member.get("name")) for member in properties]
        readonly = "yes" if any(_is_readonly(name) for name in names) else "not listed"
        lines.extend(
            [
                "",
                f"## `<{_cell(tag)}>`",
                "",
                f"**Description:** {_cell(declaration.get('description')) or 'Not documented in manifest.'}  ",
                f"**Manifest source:** `src/custom-elements.json{pointer}`  ",
                f"**Supports `readonly`:** `{readonly}`",
                "",
                "### Properties",
                "",
                "| Name | Type | Default | Description | Reflected |",
                "| --- | --- | --- | --- | --- |",
            ]
        )
        if properties:
            for member in properties:
                member_type = _text(member.get("type"))
                default = member.get("default")
                reflected = member.get("reflect")
                lines.append(
                    f"| `{_cell(member.get('name'))}` | `{_cell(member_type)}` | "
                    f"`{_cell(default)}` | {_cell(member.get('description'))} | "
                    f"`{_cell(reflected)}` |"
                )
        else:
            lines.append("| _none listed_ |  |  |  |  |")

        lines.extend(
            [
                "",
                "### Events",
                "",
                "| Name | Detail | Description |",
                "| --- | --- | --- |",
            ]
        )
        if events:
            for event in events:
                lines.append(
                    f"| `{_cell(event.get('name'))}` | `{_cell(event.get('type') or event.get('detail'))}` | "
                    f"{_cell(event.get('description'))} |"
                )
        else:
            lines.append("| _none listed_ |  |  |")

        lines.extend(
            [
                "",
                "### Slots",
                "",
                "| Name | Description |",
                "| --- | --- |",
            ]
        )
        if slots:
            for slot in slots:
                lines.append(f"| `{_cell(slot.get('name'))}` | {_cell(slot.get('description'))} |")
        else:
            lines.append("| _none listed_ |  |")

    return "\n".join(lines) + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("manifest", type=Path, help="Path to custom-elements.json")
    parser.add_argument("-o", "--output", type=Path, required=True)
    parser.add_argument(
        "--source-commit",
        default=os.environ.get("SOURCE_COMMIT", "unknown"),
    )
    parser.add_argument(
        "--generated-at",
        default=os.environ.get("GENERATED_AT", "not recorded"),
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    if not isinstance(manifest, dict):
        raise SystemExit("custom-elements manifest must be a JSON object")
    args.output.write_text(
        render(
            manifest,
            source_commit=args.source_commit,
            generated_at=args.generated_at,
        ),
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
